language: ruby
rvm:
  - 2.3.1
  - 2.2
  - 2.1
  - 2.0
cache:
  bundler: true
sudo: false
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '1.13.7'
